name: Daily auto commit

on:
  schedule:
    - cron: '0 16 * * *' # UTC 16:00 ≈ 北京时间 00:00
  workflow_dispatch:

jobs:
  daily-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate
        env:
          COZE_TOKEN: ${{ secrets.COZE_TOKEN }}
        run: npm run generate

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "blog/$(date +%F)-news" || true
          git diff --staged --quiet || git commit -m "chore: daily auto commit $(date +%F)"
          git push
