name: Daily Commit

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16:00 执行（北京时间 00:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production  # 新增：指定环境（与配置的环境名称完全一致）

    steps:
      - uses: actions/checkout@v4

      - name: 显示工作目录信息（调试）
        run: |
          pwd
          ls -la
          echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"
          echo "最新提交: $(git log -1 --oneline)"

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 安装依赖（使用 pnpm）
        run: |
          npm install -g pnpm
          pnpm install
          echo "依赖安装完成，检查 node_modules"
          ls -la node_modules || echo "node_modules 不存在"

      - name: 生成新闻内容
        run: |
          echo "开始生成新闻..."
          echo "COZE_TOKEN 是否存在: ${{ env.COZE_TOKEN != '' }}"
          pnpm run generate
        env:
          COZE_TOKEN: ${{ secrets.COZE_TOKEN }} 

      - name: 检查生成结果（调试）
        run: |
          NEWS_DIR="blog/$(date +%F)-news"
          echo "检查新闻目录: $NEWS_DIR"
          if [ -d "$NEWS_DIR" ]; then
            echo "目录存在，内容如下:"
            ls -la "$NEWS_DIR"
            echo "Markdown 内容预览:"
            cat "$NEWS_DIR/index.md" | head -n 10
          else
            echo "错误: 新闻目录 $NEWS_DIR 未生成"
            exit 1
          fi

      - name: 提交更改
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "blog/$(date +%F)-news"
          git diff --staged --quiet || git commit -m "chore: daily auto commit $(date +%F)"
          git push