name: Daily auto commit

on:
  schedule:
    - cron: '0 16 * * *'   # UTC 16:00 ≈ 北京时间 00:00
  workflow_dispatch:

jobs:
  daily-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate daily file
        run: |
          set -e
          dir="blog/$(date +%F)-news"
          file="$dir/index.md"
          mkdir -p "$dir"

          if [[ -f "$file" ]]; then
            # 文件已存在，追加
            echo "ci自动生成" >> "$file"
          else
            # 文件不存在，创建并写入首行
            echo "ci自动生成" > "$file"
          fi

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "blog/$(date +%F)-news"
          git commit -m "chore: daily auto commit $(date +%F)"
          git push